#!/usr/bin/env sh
#
# 00_Install makes sure fish is installed before doing the rcup call.
#

PM=$(sh ../../pre-setup.sh pkm)
OS=$(sh ../../pre-setup.sh os)

PKGS="fish"

for pkg in $PKGS; do
  if command -v ${pkg} > /dev/null; then
    continue
  fi

  printf "On %s and using %s as pm...\n" "${OS}" "${PM}"

  if [ "${PM}" = "brew" ] && [ "${OS}" = "mac" ]; then
      printf "will install %s with brew...\n" "${pkg}"
      brew install "${pkg}"
  elif [ "${PM}" = "xbps" ]; then
    printf "will install %s with xbps...\n" "${pkg}"
    sudo xbps-install -S "${pkg}"
  elif [ "${PM}" = "apk" ]; then
    printf "will install %s with apk...\n" "${pkg}"
    sudo apk add "${pkg}"
  elif [ "${PM}" = "apt" ]; then
    printf "will install %s with apt...\n" "${pkg}"
    sudo apt install "${pkg}"
  elif [ "${PM}" = "pacman" ]; then
    printf "will install yay with pacman and then install %s...\n" "${pkg}"
    installYay "$@"
    printf "yay installed; installing %s...\n" "${pkg}"
    yay -S "${pkg}"
  elif [ "${PM}" = "yay" ]; then
    printf "will install %s with yay...\n" "${pkg}"
    yay -S "${pkg}"
  else
    printf "can't handle your package manager, please install %s\n" "${pkg}"
    exit
  fi
done
