[aws]
symbol = "  "
disabled = true

[buf]
symbol = " "

[bun]
symbol = " "
version_format = 'v${major}.${minor}'

[c]
symbol = " "
version_format = 'v${major}.${minor}'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[✖](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold purple)'
vimcmd_replace_symbol = '[❮](bold purple)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[cpp]
symbol = " "
version_format = 'v${major}.${minor}'

[cmake]
symbol = " "
version_format = 'v${major}.${minor}'

[cmd_duration]
disabled = true

[conda]
symbol = " "
version_format = 'v${major}.${minor}'

[crystal]
symbol = " "
version_format = 'v${major}.${minor}'

[dart]
symbol = " "
version_format = 'v${major}.${minor}'

[deno]
symbol = " "
version_format = 'v${major}.${minor}'

[directory]
read_only = " 󰌾"
style = 'blue'
truncation_length = 2
truncate_to_repo = false

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
# symbol = " "
symbol = " "
style = 'white'

[git_commit]
style = 'green'
only_detached = true
tag_disabled = true
tag_symbol = '  '

[git_metrics]
added_style = 'green'
deleted_style = 'red'
disabled = true

[git_state]
style = 'yellow'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
modified = '*'
style = 'red'

[golang]
format = '[$symbol($version )]($style)'
style = 'cyan'
symbol = " "
version_format = 'v${major}.${minor}'

[guix_shell]
symbol = " "

[haskell]
symbol = " "
version_format = 'v${major}.${minor}'

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
version_format = 'v${major}.${minor}'

[julia]
symbol = " "
version_format = 'v${major}.${minor}'

[kotlin]
symbol = " "
version_format = 'v${major}.${minor}'

[lua]
symbol = " "
version_format = 'v${major}.${minor}'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "
version_format = 'v${major}.${minor}'

[nim]
symbol = "󰆥 "
version_format = 'v${major}.${minor}'

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
version_format = 'v${major}.${minor}'

[ocaml]
symbol = " "
version_format = 'v${major}.${minor}'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
format = '[$symbol$version]($style) '
symbol = "󰏗 "
style = '208'

[perl]
symbol = " "
version_format = 'v${major}.${minor}'

[php]
symbol = " "
version_format = 'v${major}.${minor}'

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "
version_format = 'v${major}.${minor}'

[rlang]
symbol = "󰟔 "
version_format = 'v${major}.${minor}'

[ruby]
symbol = " "
version_format = 'v${major}.${minor}'

[rust]
format = '[$symbol($version )]($style)'
style = 'red'
symbol = "󱘗 "
version_format = 'v${major}.${minor}'

[scala]
symbol = " "
version_format = 'v${major}.${minor}'

[swift]
symbol = " "
version_format = 'v${major}.${minor}'

[terraform]
format = '[$symbol]($style) '
symbol = "󱁢"

[zig]
symbol = " "
version_format = 'v${major}.${minor}'

[gradle]
symbol = " "
version_format = 'v${major}.${minor}'
