#!/usr/bin/env sh

if !(grep -q "fish" /etc/shells); then
  echo "fish not found in /etc/shells, adding it"
  echo $(command -v fish) | sudo tee -a /etc/shells
fi

echo "setting fish as default shell"
chsh -s $(command -v fish)
